name: lint
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Check code style
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
      - uses: bahmutov/npm-install@v1
      - run: npm run lint
